$(window).on("load",function(){var d=$(".volosunov");d.find(".spinner").delay(650).fadeOut("slow");d.delay(650).fadeOut("slow");$(".mov_fadeIn_start").addClass("animated fadeIn");$(".mov_fadeIn_start").css("opacity","1");$(".mov_fadeInUp_start").addClass("animated fadeInUp");$(".mov_zoomIn_start").css("opacity","1");$(".mov_zoomIn_start").addClass("animated zoomIn");$(".load_active").addClass("active");$.each($(".mov1_left_one_by_one_start p"),function(c,a){setTimeout(function(){$(a).addClass("animated fadeInLeft")},
300*c)})});
$(document).ready(function(){function d(){$(".mov_next_fadeInUp").each(function(){var a=$(this).offset().top,b=$(window).scrollTop();a<b+c+250?$(this).addClass("animated fadeInUp"):$(this).removeClass("animated fadeInUp")});$(".mov_tile_js").each(function(){var a=$(this).offset().top,b=$(window).scrollTop();a<b+c?$.each($(this).find(".iner_tile"),function(a,b){setTimeout(function(){$(b).addClass("animated flipInX")},250*a)}):$(this).find(".iner_tile").removeClass("animated flipInX")});$("section ul").each(function(){var a=
$(this).offset().top,b=$(window).scrollTop();a<b+c?$.each($(this).find("li"),function(a,b){setTimeout(function(){$(b).addClass("animated fadeIn")},250*a)}):$(this).find("li").removeClass("animated fadeIn")});$(".mov_next_fadeInLeft").each(function(){var a=$(this).offset().top,b=$(window).scrollTop();a<b+c?$(this).addClass("animated fadeInLeft"):$(this).removeClass("animated fadeInLeft")});$(".mov_next_fadeInRight").each(function(){var a=$(this).offset().top,b=$(window).scrollTop();a<b+c?$(this).addClass("animated fadeInRight"):
$(this).removeClass("animated fadeInRight")});$(".mov_next_fadeIn").each(function(){var a=$(this).offset().top,b=$(window).scrollTop();a<b+c?$(this).addClass("animated fadeIn"):$(this).removeClass("animated fadeIn")});$(".mov_next_fadeIn_timeOut").each(function(){var a=$(this).offset().top,b=$(window).scrollTop();a<b+c?$.each($(this).find("div.col-12"),function(a,b){setTimeout(function(){$(b).addClass("animated fadeIn")},300*a)}):$(this).find("div.col-12").removeClass("animated fadeIn")});$(".mov_slideInLeft").each(function(){var a=
$(this).offset().top,b=$(window).scrollTop();a<b+c?$.each($(this).find("div.col"),function(a,b){setTimeout(function(){$(b).addClass("animated fadeInLeft")},80*a)}):$(this).find("div.col").removeClass("animated fadeInLeft")})}window.oncontextmenu=function(){return!1};document.addEventListener("mousemove",function(a){"on"==a.target.getAttribute("unselectable")&&a.target.ownerDocument.defaultView.getSelection().removeAllRanges()},!1);$(".button_mobi_menu").on("click",function(){$(this).hasClass("active")?
($(".button_mobi_menu").removeClass("active"),$(".menu_div").removeClass("active")):($(".button_mobi_menu").addClass("active"),$(".menu_div").addClass("active"))});$(".menu_top li:not(.price_menu_modal)").on("click",function(){$(".button_mobi_menu").removeClass("active");$(".menu_div").removeClass("active")});$(".menu_top a").mPageScroll2id({scrollSpeed:900,scrollEasing:"swing",scrollingEasing:"swing",offset:80});$("a.go_a").mPageScroll2id({scrollSpeed:900,scrollEasing:"swing",scrollingEasing:"swing",
offset:80});$(".tab_js."+$(".tabs_js.active").attr("data-tab")).fadeIn(200);$(".tabs_js").on("click",function(a){a.preventDefault();$(this).hasClass("active")||(a=$(this).attr("data-tab"),$(".tabs_js").removeClass("active"),$(".tab_js").css("display","none"),$(".tab_js."+a).fadeIn(400),$(this).addClass("active"))});$(".card_tile_js."+$(".click_tile_js.active").attr("data-card")).fadeIn(200);$(".click_tile_js").on("click",function(a){a.preventDefault();$(this).hasClass("active")||(a=$(this).attr("data-card"),
$(".click_tile_js").removeClass("active"),$(".card_tile_js").css("display","none"),$(".card_tile_js."+a).fadeIn(400),$(this).addClass("active"))});var c=$(window).height();0<$(this).scrollTop()&&$(".menu_div").addClass("scroll");d();$(window).scroll(function(){0<$(this).scrollTop()&&$(".menu_div").addClass("scroll");0==$(this).scrollTop()&&$(".menu_div").removeClass("scroll");d()});$("#sps").on("click","div",function(){$("#sps").modal("toggle")});$("#manedj_form").submit(function(){var a=$(this);
$.ajax({type:"POST",url:"zakaz.php",data:a.serialize()}).done(function(){a.trigger("reset");$("#exampleModal_1").modal("toggle");setTimeout(function(){$("#sps").modal("toggle")},250)});return!1});$("#perezvon_form").submit(function(){var a=$(this);$.ajax({type:"POST",url:"zakaz.php",data:a.serialize()}).done(function(){a.trigger("reset");$("#exampleModal_2").modal("toggle");setTimeout(function(){$("#sps").modal("toggle")},250)});return!1});$("#katalog_form").submit(function(){var a=$(this);$.ajax({type:"POST",
url:"zakaz.php",data:a.serialize()}).done(function(){a.trigger("reset");$("#exampleModal_3").modal("toggle");setTimeout(function(){$("#sps").modal("toggle")},250)});return!1});$("#vopros_form").submit(function(){var a=$(this);$.ajax({type:"POST",url:"vopros.php",data:a.serialize()}).done(function(){a.trigger("reset");$(".button_form_vopros").addClass("good");$(".button_form_vopros").text("\u0412\u043e\u043f\u0440\u043e\u0441 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d!");$(".button_form_vopros").attr("disabled",
!0)});return!1})});